import chromadb
from chromadb.config import Settings
import os

class VectorDB:
    def __init__(self, collection_name="career_path_gpt", persist_directory="./chroma_db"):
        """
        Initializes the ChromaDB client and collection.
        """
        # Ensure persist directory exists
        if not os.path.exists(persist_directory):
            os.makedirs(persist_directory)
            
        self.client = chromadb.PersistentClient(path=persist_directory)
        
        self.collection = self.client.get_or_create_collection(name=collection_name)
        print(f"Connected to ChromaDB collection: {collection_name}")

    def add_documents(self, documents, metadatas, ids):
        """
        Adds documents and their embeddings to the collection.
        Note: ChromaDB handles embedding generation automatically if no embeddings are provided,
        but we can also pass pre-computed embeddings if we want to use our custom engine.
        For now, we will let ChromaDB use its default or pass embeddings explicitly if needed.
        
        Actually, to be consistent with our architecture, we should probably pass embeddings 
        generated by our EmbeddingEngine. But Chroma's add method takes embeddings as an optional arg.
        """
        self.collection.add(
            documents=documents,
            metadatas=metadatas,
            ids=ids
        )
        print(f"Added {len(documents)} documents to the collection.")

    def add_documents_with_embeddings(self, documents, embeddings, metadatas, ids):
        """
        Adds documents with pre-computed embeddings.
        """
        self.collection.add(
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas,
            ids=ids
        )
        print(f"Added {len(documents)} documents with embeddings to the collection.")

    def query(self, query_text, n_results=5):
        """
        Queries the collection using text (Chroma computes embedding).
        """
        results = self.collection.query(
            query_texts=[query_text],
            n_results=n_results
        )
        return results

    def query_by_embedding(self, query_embedding, n_results=5):
        """
        Queries the collection using a pre-computed embedding.
        """
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )
        return results

if __name__ == "__main__":
    # Test the VectorDB
    # Note: This test relies on Chroma's default embedding function for simplicity in this standalone run
    # In integration, we will use our EmbeddingEngine.
    db = VectorDB(persist_directory="./test_chroma_db")
    
    docs = ["Software Engineer", "Data Scientist", "Nurse", "Chef"]
    metas = [{"category": "Tech"}, {"category": "Tech"}, {"category": "Healthcare"}, {"category": "Hospitality"}]
    ids = ["1", "2", "3", "4"]
    
    db.add_documents(docs, metas, ids)
    
    results = db.query("I like coding and python", n_results=2)
    print("Query Results:", results)
